### ISSUE TITLE
go run on Windows error

### ISSUE THREAD

**Issue by MawuliStephen** [OpenStruct/goeasycli#31]
2024/07/17 15:10:42 C:/WINDOWS/system32/justGo/database/database.go:66
[error] failed to initialize database, got error Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
failed to connect database
Database connection is nil. cannot run migration
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x13e4992]

**Comment by noahalorwu** [comment]
@MawuliStephen we would look into this issue. Thanks for letting us know of this 😊

**Comment by noahalorwu** [comment]
To resolve this issue on Windows first run this command in your `cmd/powershell `
`go env -w CGO_ENABLED =1`

Afterwards, download this tdm-gcc from the link below for your respective architecture 
https://jmeubank.github.io/tdm-gcc

During installation do select `TDM-GCC Recommend, All Packages` from the Choose Components Screen. See Screenshot
![gcc](https://github.com/user-attachments/assets/44b06ab8-8f94-4b21-82bb-ba4b0c1f1cec)

@theHinneh  you need to add this section to the documentation 😊

**Comment by theHinneh** [comment]
The fix for this has been added to the documentation.
